# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: NussiSNMP add-on
version: "1.0.2"
slug: nussi_snmp
description: NussiSNMP add-on
url: "https://github.com/DaNussi/ha-addons/tree/main/nussi_snmp"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
